name = "web"
# account_id = "2575000dd90a08dbbeb2b8cca2e64775" # scraper.workers.dev
account_id = "75e1f5c9f491c69a403528a3f9d9e8ad" # scraper.workers.dev
type = "webpack"
workers_dev = true
main = "./index.js"
compatibility_date = "2022-09-18"